### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by Sadorrow99** [ceramicskate0/YAKSR#18]
Got this error:

                            Traceback (most recent call last):
                           File "./GetClones.py", line 21, in <module>
                           os.makedirs(str(currentdir)+"/ToolBox/"+str(dirname))
                           File "/usr/lib/python2.7/os.py", line 157, in makedirs
                            mkdir(name, mode)
                          OSError: [Errno 17] File exists: '/root/TheCollective/ToolBox/KEYLOGGER'

Any suggestions? Cheers.

**Comment by seajaysec** [comment]
@Sadorrow99 my janky method of getting around this was to comment out line 21 in GetClones.py. Then I manually created any directories in /Toolbox/ that it complained weren't present.

**Comment by ceramicskate0** [comment]
Unfortunately, i was not able to reproduce issue. However, based on what chrsjhnsn said works for them, I have wrapped the method in a try/catch to avoid crash and issue and should now (assuming folder exits)  not occur. Could you give it a try let me know if the issue persists?

**Comment by ceramicskate0** [comment]
Im going to close for now. If the issue occures again please reopen or create new bug report. Thanks!
